laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Lang;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('empresas', 'EmpresasController@index')->name('empresas');
    Route::get('quem-somos', 'QuemSomosController@index')->name('quem-somos');
    Route::get('novidades', 'NovidadesController@index')->name('novidades');
    Route::get('novidades/busca', 'NovidadesController@busca')->name('novidades.busca');
    Route::get('novidades/{novidade_categoria_slug}', 'NovidadesController@categoria')->name('novidades.categoria');
    Route::get('novidades/{novidade_categoria_slug}/{novidade_slug}', 'NovidadesController@show')->name('novidades.show');
    Route::get('contato', 'ContatoController@index')->name('contato');
    // Route::get('contatos', 'ContatoController@index2')->name('contatos');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::get('termos-de-uso', 'TermosDeUsoController@index')->name('termos-de-uso');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::get('candidato', 'CandidatosController@index')->name('candidato');
    Route::get('trainees/pdf', 'HomeController@openPdf')->name('trainees.pdf');
    Route::get('trainees', function() {
        return view('frontend.trainees');
    })->name('trainees');
    Route::get('consultor', function() {
        return view('frontend.consultor', ['contratacao' => \App\Models\Contratacao::first()]);
    })->name('consultor');

    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');
    Route::post('newsletter', 'NewsletterController@post')->name('newsletter.post');

    Route::get('blog', 'BlogController@index')->name('blog');
    Route::get('blog/{post}', 'BlogController@show')->name('post.detalhes');

    // Internacionalização
    Route::get('lang/{lang}', function($lang) {
        if (in_array($lang, ['pt', 'en', 'es'])) {
            Session::put('locale', $lang);
        }
        return back();
    })->name('lang');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function() {
        Route::get('/', 'PainelController@index')->name('painel');

        /* GENERATED ROUTES */
        Route::resource('empresas', 'EmpresasController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('empresas.servicos', 'EmpresasServicosController');
		Route::resource('novidades/categorias', 'NovidadesCategoriasController', ['parameters' => ['categorias' => 'categorias_novidades']]);
		Route::resource('novidades', 'NovidadesController');
		Route::resource('contratacao', 'ContratacaoController', ['only' => ['index', 'update']]);
		Route::resource('depoimentos-candidatos', 'DepoimentosCandidatosController');
		Route::resource('depoimentos', 'DepoimentosController');
		Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
		Route::resource('nossa-lideranca', 'NossaLiderancaController');
		Route::resource('estrutura', 'EstruturaController');
		Route::resource('clientes', 'ClientesController');
		Route::resource('quem-somos', 'QuemSomosController', ['only' => ['index', 'update']]);
		Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
		Route::resource('termos-de-uso', 'TermosDeUsoController', ['only' => ['index', 'update']]);
		Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('usuarios', 'UsuariosController');

        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');
        Route::get('newsletter', 'NewsletterController@index')->name('painel.newsletter.index');
        Route::get('newsletter/export', 'NewsletterController@export')->name('painel.newsletter.export');

		Route::resource('blog/pagina', 'BlogController', ['only' => ['index', 'update']]);
		Route::resource('blog/posts', 'PostsController');
        Route::get('blog/posts/{post}/imagens/clear', [
            'as'   => 'painel.blog.posts.imagens.clear',
            'uses' => 'PostsImagensController@clear'
        ]);
		Route::resource('blog/posts.imagens', 'PostsImagensController', ['parameters' => ['imagens' => 'posts_imagens']]);

        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

        Route::get('generator', 'GeneratorController@index')->name('generator.index');
        Route::post('generator', 'GeneratorController@submit')->name('generator.submit');
    });

    // Auth
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function() {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/BlogController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\BlogRequest;
use App\Models\Blog;

class BlogController extends Controller
{
    public function index()
    {
        $blog = Blog::first();

        return view('painel.blog.pagina.edit', compact('blog'));
    }

    public function update(BlogRequest $request, $blog)
    {
        try {
            $input = $request->all();
            $blog = Blog::where('id', $blog)->first();

            $blog->update($input);

            return redirect()->route('painel.blog.pagina.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ClientesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ClientesRequest;
use App\Http\Controllers\Controller;

use App\Models\Cliente;

class ClientesController extends Controller
{
    public function index()
    {
        $registros = Cliente::ordenados()->get();

        return view('painel.clientes.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.clientes.create');
    }

    public function store(ClientesRequest $request)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Cliente::upload_imagem();

            Cliente::create($input);

            return redirect()->route('painel.clientes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Cliente $registro)
    {
        return view('painel.clientes.edit', compact('registro'));
    }

    public function update(ClientesRequest $request, Cliente $registro)
    {
        try {

            $input = $request->all();

            if (isset($input['imagem'])) $input['imagem'] = Cliente::upload_imagem();

            $registro->update($input);

            return redirect()->route('painel.clientes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Cliente $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.clientes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ConfiguracoesController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ConfiguracoesRequest;
use App\Http\Controllers\Controller;

use App\Models\Configuracoes;

class ConfiguracoesController extends Controller
{
    public function index()
    {
        $registro = Configuracoes::first();

        return view('painel.configuracoes.edit', compact('registro'));
    }

    public function update(ConfiguracoesRequest $request, Configuracoes $registro)
    {
        try {
            $input = $request->all();

            if (isset($input['imagem_de_compartilhamento'])) $input['imagem_de_compartilhamento'] = Configuracoes::upload_imagem_de_compartilhamento();

            $registro->update($input);

            return redirect()->route('painel.configuracoes.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/ContatoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContatoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contato;

class ContatoController extends Controller
{
    public function index()
    {
        $contato = Contato::first();

        return view('painel.contato.index', compact('contato'));
    }

    public function update(ContatoRequest $request, Contato $contato)
    {
        try {

            $input = $request->all();

            $contato->update($input);
            return redirect()->route('painel.contato.index')->with('success', 'Informações alteradas com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar informações: '.$e->getMessage()]);

        }
    }

}

laravel/app/Http/Controllers/Painel/ContatosRecebidosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Models\ContatoRecebido;

class ContatosRecebidosController extends Controller
{
    public function index()
    {
        $contatosrecebidos = ContatoRecebido::orderBy('created_at', 'DESC')->get();

        return view('painel.contato.recebidos.index', compact('contatosrecebidos'));
    }

    public function show(ContatoRecebido $contato)
    {
        $contato->update(['lido' => 1]);

        return view('painel.contato.recebidos.show', compact('contato'));
    }

    public function destroy(ContatoRecebido $contato)
    {
        try {

            $contato->delete();
            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem excluída com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir mensagem: '.$e->getMessage()]);

        }
    }

    public function toggle(ContatoRecebido $contato, Request $request)
    {
        try {

            $contato->update([
                'lido' => !$contato->lido
            ]);

            return redirect()->route('painel.contato.recebidos.index')->with('success', 'Mensagem alterada com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar mensagem: '.$e->getMessage()]);

        }
    }
}

laravel/app/Http/Controllers/Painel/ContratacaoController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\ContratacaoRequest;
use App\Http\Controllers\Controller;

use App\Models\Contratacao;

class ContratacaoController extends Controller
{
    public function index()
    {
        $registro = Contratacao::first();

        return view('painel.contratacao.edit', compact('registro'));
    }

    public function update(ContratacaoRequest $request, Contratacao $registro)
    {
        try {
            $input = $request->all();


            $registro->update($input);

            return redirect()->route('painel.contratacao.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {
            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/DepoimentosCandidatosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Http\Requests\DepoimentosCandidatosRequest;
use App\Models\DepoimentoCandidato;

class DepoimentosCandidatosController extends Controller
{
    public function index()
    {
        $depoimentos = DepoimentoCandidato::ordenados()->get();

        return view('painel.depoimentos-candidatos.index', compact('depoimentos'));
    }

    public function create()
    {
        return view('painel.depoimentos-candidatos.create');
    }

    public function store(DepoimentosCandidatosRequest $request)
    {
        try {
            $input = $request->all();

            DepoimentoCandidato::create($input);

            return redirect()->route('painel.depoimentos-candidatos.index')->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(DepoimentoCandidato $depoimento)
    {
        return view('painel.depoimentos-candidatos.edit', compact('depoimento'));
    }

    public function update(DepoimentosCandidatosRequest $request, DepoimentoCandidato $depoimento)
    {
        try {
            $input = $request->all();

            $depoimento->update($input);

            return redirect()->route('painel.depoimentos-candidatos.index')->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(DepoimentoCandidato $depoimento)
    {
        try {
            $depoimento->delete();

            return redirect()->route('painel.depoimentos-candidatos.index')->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/DepoimentosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Requests\DepoimentosRequest;
use App\Http\Controllers\Controller;

use App\Models\Depoimento;

class DepoimentosController extends Controller
{
    public function index()
    {
        $registros = Depoimento::ordenados()->get();

        return view('painel.depoimentos.index', compact('registros'));
    }

    public function create()
    {
        return view('painel.depoimentos.create');
    }

    public function store(DepoimentosRequest $request)
    {
        try {

            $input = $request->all();

            Depoimento::create($input);

            return redirect()->route('painel.depoimentos.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: '.$e->getMessage()]);

        }
    }

    public function edit(Depoimento $registro)
    {
        return view('painel.depoimentos.edit', compact('registro'));
    }

    public function update(DepoimentosRequest $request, Depoimento $registro)
    {
        try {

            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.depoimentos.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: '.$e->getMessage()]);

        }
    }

    public function destroy(Depoimento $registro)
    {
        try {

            $registro->delete();

            return redirect()->route('painel.depoimentos.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: '.$e->getMessage()]);

        }
    }

}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.aceite-de-cookies*')) class="active" @endif>
                            <a href="{{ route('painel.aceite-de-cookies') }}">Aceite de Cookies</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav" style="margin-left: 20px;">
    <li class="dropdown @if(Tools::routeIs(['painel.home*', 'painel.depoimentos*'])) active @endif">
        <a href="#" class="dropdown-toggle link-nav-painel" data-toggle="dropdown">Home <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.home*')) class="active" @endif>
                <a href="{{ route('painel.home.index') }}" class="link-nav-painel">Home</a>
            </li>
            <li @if(Tools::routeIs('painel.depoimentos.*')) class="active" @endif>
                <a href="{{ route('painel.depoimentos.index') }}" class="link-nav-painel">Depoimentos</a>
            </li>
            <li @if(Tools::routeIs('painel.depoimentos-candidatos*')) class="active" @endif>
                <a href="{{ route('painel.depoimentos-candidatos.index') }}" class="link-nav-painel">Depoimentos Candidatos</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.empresas*')) class="active" @endif>
        <a href="{{ route('painel.empresas.index') }}" class="link-nav-painel">Empresas do Grupo</a>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.quem-somos*', 'painel.clientes*', 'painel.estrutura*'])) active @endif">
        <a href="#" class="dropdown-toggle link-nav-painel" data-toggle="dropdown">Quem Somos <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.quem-somos*')) class="active" @endif>
                <a href="{{ route('painel.quem-somos.index') }}" class="link-nav-painel">Quem Somos</a>
            </li>
            <li @if(Tools::routeIs('painel.clientes*')) class="active" @endif>
                <a href="{{ route('painel.clientes.index') }}" class="link-nav-painel">Clientes</a>
            </li>
            <li @if(Tools::routeIs('painel.estrutura*')) class="active" @endif>
                <a href="{{ route('painel.estrutura.index') }}" class="link-nav-painel">Estrutura</a>
            </li>
            <li @if(Tools::routeIs('painel.nossa-lideranca*')) class="active" @endif>
                <a href="{{ route('painel.nossa-lideranca.index') }}" class="link-nav-painel">Nossa Liderança</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.novidades*')) class="active" @endif>
        <a href="{{ route('painel.novidades.index') }}" class="link-nav-painel">Novidades</a>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.termos-de-uso*', 'painel.politica-de-privacidade*', 'painel.contratacao*'])) active @endif">
        <a href="#" class="dropdown-toggle link-nav-painel" data-toggle="dropdown">Textos <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.termos-de-uso*')) class="active" @endif>
                <a href="{{ route('painel.termos-de-uso.index') }}" class="link-nav-painel">Termos de Uso</a>
            </li>
            <li @if(Tools::routeIs('painel.politica-de-privacidade*')) class="active" @endif>
                <a href="{{ route('painel.politica-de-privacidade.index') }}" class="link-nav-painel">Política de Privacidade</a>
            </li>
            <li class="divider"></li>
            <li @if(Tools::routeIs('painel.contratacao*')) class="active" @endif>
                <a href="{{ route('painel.contratacao.index') }}" class="link-nav-painel">Contratação</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.newsletter*')) class="active" @endif>
        <a href="{{ route('painel.newsletter.index') }}" class="link-nav-painel">Newsletter</a>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.blog*'])) active @endif">
        <a href="#" class="dropdown-toggle link-nav-painel" data-toggle="dropdown">Blog <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.blog.pagina*')) class="active" @endif>
                <a href="{{ route('painel.blog.pagina.index') }}" class="link-nav-painel">Página</a>
            </li>
            <li @if(Tools::routeIs('painel.blog.posts*')) class="active" @endif>
                <a href="{{ route('painel.blog.posts.index') }}" class="link-nav-painel">Posts</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs('painel.contato*')) active @endif">
        <a href="#" class="dropdown-toggle link-nav-painel" data-toggle="dropdown">Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.contato.index')) class="active" @endif>
                <a href="{{ route('painel.contato.index') }}" class="link-nav-painel">Informações de Contato</a>
            </li>
            <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.contato.recebidos.index') }}" class="link-nav-painel">Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>
</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">

    
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"><\/script>')</script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>
</body>
</html>